---
title: "vaccine compartment"
author: "ZHE ZHENG"
date: "7/30/2020"
output: html_document
---
## new parameters for passive immunization
###equations
$$$$


```{r}
v=0.9
eff=0.784
omega_v=1/32

#Initialize a vector to keep track of the number of people in each Svate
Sv0=c()
Sv0[1:al]=c((N[1:6]*(1-v*eff)), rep(0,al-6))#Maternal immunity
Sv0[(al+1):(2*al)]=c((N[1:12]*v*eff),rep(0,al-12))#immunoprophylaxis immunity
Sv0[(2*al+1):(3*al)]=c(rep(0,6),N[7:12]*(1-v*eff),N[13:al]-rep(1,al-12))#Susceptible_0
Sv0[(3*al+1):(4*al)]=c(rep(0,12),rep(1,al-12))#Infectious_1 (primary) 
Sv0[(4*al+1):(5*al)]=rep(0,al)#Susceptible_1
Sv0[(5*al+1):(6*al)]=rep(0,al)#Infectious_2 (2nd time)
Sv0[(6*al+1):(7*al)]=rep(0,al)#Susceptible_2
Sv0[(7*al+1):(8*al)]=rep(0,al)#Infectious_3
Sv0[(8*al+1):(9*al)]=rep(0,al)#Susceptible_3+
Sv0[(9*al+1):(10*al)]=rep(0,al)#Infectious_A 

# Sv0 <- matrix(data=Sv0,nrow=10,ncol=21,byrow = T)
# colnames(Sv0) <- age
# rownames(Sv0) <- c("M","Mv","S0","I1","S1","I2","S2","I3","S3","I4")

```

## model Svructure for passive immunization
```{r}
library(deSolve)
# this is an age Svructured MSIS model
############# Model Equations ######################

passive_immune <- function(times,x,pars){
  
  nage <- al 
  M    = x[1:nage]
  Mv   = x[(nage+1):(2*nage)]
  S0    = x[(2*nage+1):(3*nage)]
  I1    = x[(3*nage+1):(4*nage)]
  S1    = x[(4*nage+1):(5*nage)]
  I2    = x[(5*nage+1):(6*nage)]
  S2    = x[(6*nage+1):(7*nage)]
  I3    = x[(7*nage+1):(8*nage)]
  S3    = x[(8*nage+1):(9*nage)]
  I4    = x[(9*nage+1):(10*nage)]
  
  dx <- rep(0,10*al)

  lambda=(1+b1*cos(2*pi*(times-phi*52.18)/52.18))%*%t(x[(3*al+1):(4*al)]+rho1*x[(5*al+1):(6*al)]+rho2*x[(7*al+1):(8*al)]+rho2*x[(9*al+1):(10*al)])%*%beta/sum(x)
  
	for (a in 1:nage) {
	  
	  dx[a] <- (1-v*eff)*log(B[times,a]+1)/52*sum(x)-(omega+(u[a]+um))*M[a] #dM/dt
		dx[a+nage] <- v*eff*log(B[times,a]+1)/52*sum(x)-(omega_v+(u[a]+um))*Mv[a] #dMv/dt
		dx[a+2*nage]<- omega*M[a]+omega_v*Mv[a]-sum(lambda[,a])*S0[a]-(u[a]+um)*S0[a] #dS0/dt
		 dx[a+3*nage]<- sum(lambda[,a])*S0[a]- gamma1*I1[a]-(u[a]+um)*I1[a] #dI1/dt
		 dx[a+4*nage]<- gamma1*I1[a]-sigma1*sum(lambda[,a])*S1[a]-(u[a]+um)*S1[a] #dS1/dt
		 dx[a+5*nage]<- sigma1*sum(lambda[,a])*S1[a]- gamma1*I2[a]-(u[a]+um)*I2[a] #dI2/dt
		 dx[a+6*nage]<- gamma1*I2[a]- sigma2*sum(lambda[,a])*S2[a]-(u[a]+um)*S2[a] #dS2/dt
		 dx[a+7*nage]<- sigma2*sum(lambda[,a])*S2[a]-gamma2*I3[a]-(u[a]+um)*I3[a] #dI3/dt
		 dx[a+8*nage]<- gamma2*I3[a]-sigma3*sum(lambda[,a])*S3[a]+gamma3*I4[a]-(u[a]+um)*S3[a] #dS3/dt
		dx[a+9*nage] <- sigma3*sum(lambda[,a])*S3[a]-gamma3*I4[a]-(u[a]+um)*I4[a] #dI4/dt
		
		if (a >1 ){
		dx[a] <- dx[a]+ u[a-1]*M[a-1]
		dx[a+nage] <- dx[a+nage] + u[a-1]*Mv[a-1]
		dx[a+2*nage] <- dx[a+2*nage] + u[a-1]*S0[a-1]
		dx[a+3*nage] <-dx[a+3*nage]+u[a-1]*I1[a-1]
		dx[a+4*nage] <- dx[a+4*nage]+u[a-1]*S1[a-1]
		dx[a+5*nage] <- dx[a+5*nage]+u[a-1]*I2[a-1]
		dx[a+6*nage] <- dx[a+6*nage]+u[a-1]*S2[a-1]
		dx[a+7*nage] <- dx[a+7*nage]+u[a-1]*I3[a-1]
		dx[a+8*nage] <- dx[a+8*nage]+u[a-1]*S3[a-1]
		dx[a+9*nage] <- dx[a+9*nage]+u[a-1]*I4[a-1]
		}
	}
	
	return(list(dx))}

##################################################################################
# set up some initial conditions at time t=0
##################################################################################

############ Setting Initial Conditions ###############

my_yinit <- Sv0

############### Setting Time Frame ####################

Start_time = 1 # Start date (years)
# end_time = 25 # end date (years)
my_times <- seq(Start_time, tmax, by = 1) # gives a sequence from Svart to end
											 # in increments of 1

################## Setting Parameters ##################

beta = beta
b1=b1
phi=phi
rho1 = ri2
rho2 = ri3
gamma1=d1
gamma2=d2
gamma3=d3
omega=wm
u=u
um=um
B=B
sigma1=rr1
sigma2=rr2
sigma3=rr3
#lambda1=rsvmatdata$lambda

Immune_parms<-list(B=B,omega=omega,omega_v=omega_v,v=v,eff=eff,u=u,um=um,beta=beta,b1=b1,phi=phi,rho1=rho1,rho2=rho2, gamma1=gamma1,sigma1=sigma1,gamma2=gamma2,sigma2=sigma2,gamma3=gamma3,sigma3=sigma3)

############# Running The Model ####################

Immune_results <- as.data.frame(ode(y=Sv0, times=my_times, func=passive_immune,events=list(func = posfun, time = c(1:tmax)),parms=Immune_parms, method='lsoda'))

Sv <- Immune_results[,-1]
Sv <- tail(Sv,1225)

Sv <- as.matrix(Sv)
```

```{r}
#Initialize matrices to keep track of the outcomes of interest
lambda=matrix(0,nrow=tmax-t0,ncol=al)#Force of infection
Pop=matrix(0,nrow=tmax-t0,ncol=al)#Total population size of each age group
C=matrix(0,nrow=tmax-t0,ncol=al)#Number of symptomatic cases by age
H=matrix(0,nrow=tmax-t0,ncol=al)#Number of hospitalizations by age
Prev=matrix(0,nrow=tmax-t0,ncol=al)#Prevalence of infection by age
Incid=matrix(0,nrow=tmax-t0,ncol=al)#Incidence of infection by age

for (t in 1:1225)
    {lambda[t,] <- as.vector((1+b1*cos(2*pi*(t-phi*52.18)/52.18))*((Sv[t,(3*al+1):(4*al)]+rho1*Sv[t,(5*al+1):(6*al)]+rho2*Sv[t,(7*al+1):(8*al)]+rho2*Sv[t,(9*al+1):(10*al)])%*%beta)/sum(Sv[t,]))}
    #lambda(t,:)=(1+b1*cos(2*pi*(time(t)-phi*52.18)/52.18))*((St(t,2*al+1:3*al)+ri2*St(t,4*al+1:5*al)+ri3*St(t,6*al+1:7*al)+ri3*St(t,8*al+1:9*al))*(beta*school(round(time(t)))+betaH*(1-school(round(time(t))))))/(sum(St(t,:))^q)

for (i in 1:10) #sum across the 10 different infection states of the model
{Pop <- Pop+Sv[,(al*(i-1)+1):(al*i)]}

#Other outcomes of interest
for (i in 1:al){
    C[,i] <- delta1[i]*Sv[,(2*al+i)]*lambda[,i]+delta2[i]*rr1*Sv[,(4*al+i)]*lambda[,i]+delta3[i]*rr2*Sv[,(6*al+i)]*lambda[,i]+delta3[i]*rr3*Sv[,(8*al+i)]*lambda[,i]
    
    H[,i]=hosp1[i]*Sv[,(2*al+i)]*lambda[,i]+hosp2[i]*rr1*Sv[,(4*al+i)]*lambda[,i]+hosp3[i]*rr2*Sv[,(6*al+i)]*lambda[,i]+hosp4[i]*rr3*Sv[,(8*al+i)]*lambda[,i]
    
    Incid[,i]=Sv[,(2*al+i)]*lambda[,i]+rr1*Sv[,(4*al+i)]*lambda[,i]+rr2*Sv[,(6*al+i)]*lambda[,i]+rr3*Sv[,(8*al+i)]*lambda[,i]
    
    Prev[,i]=Sv[,(3*al+i)]+Sv[,(5*al+i)]+Sv[,(7*al+i)]+Sv[,(9*al+i)]}

#Age distribution of hospitalized cases
A=(H/(rowSums(H)%*%t(rep(1,al))))*avgage #Average age of cases (by week)
agedata <- matrix(0,nrow =1225 ,ncol =5 )
agedata[,1] <- rowSums(H[, 1:12])
agedata[,2:5] <- H[, 13:16]
agedist=colSums(agedata)/sum(colSums(H[,1:16])) #Summary age distribution of hospitalized cases
agedist <- t(matrix(agedist))
colnames(agedist) <- c("<1yr","1yr","2yr","3yr","4yr")
#Age distribution of population
#St <- matriSt(0,nrow=3364,ncol = 189)
popagedist=colMeans(Sv[,1:al]+Sv[,(al+1):(2*al)]+Sv[,(2*al+1):(3*al)]+Sv[,(3*al+1):(4*al)]+Sv[,(4*al+1):(5*al)]+Sv[,(5*al+1):(6*al)]+Sv[,(6*al+1):(7*al)]+Sv[,(7*al+1):(8*al)]+Sv[,(8*al+1):(9*al)]+Sv[,(9*al+1):(10*al)])/(mean(rowSums(Sv)))

popagedist=c(sum(popagedist[1:16]), sum(popagedist[17:18]),popagedist[19:al])#Aggregated into <5y, 5-20y, 20-40y, 40-60y, 60+y
popagedist <- t(matrix(popagedist))
colnames(popagedist) <- c("0-5","5-15","20-40","40-60","60+")


#Week of peak RSV cases in each year
# peak=rep(0,length(H))#=1 if number of cases is greater than week before and after, =0 otherwise
# for (i in 2:length(H)-1){
#     if (sum(H[i,])>sum(H[i-1,]) & sum(H[i,])>sum(H[i+1,]))
#     {peak[i,1]=1}}

#ploc=rem(which(peak==1),52)#Week of peak activity = remainder when you divide the indices of where peak > 0 by 52

par(mfrow=c(2,2))
# plot 'Number of hospitalizations' by year vs 'Proportion of cases' by age
plot(x=1:1225,y=rowSums(H),type="l",xlab="date",ylab="#hospitalizations",main='Number of hospitalizations')

barplot(agedist, main="proportion of hospitalization by age")

barplot(popagedist, main="proportion of cases by age")

# plot the population size (by years) and age distribution
plot(x=1:1225,y=rowSums(Pop),type="l",xlab="date",ylab="population size",main='Population Size')

```
##comparison (immuned vs non)
```{r}
plot(x=1:1225,y=rowSums(C1),type="l",xlab="date",ylab="#cases",main='Number of cases',col="red")
lines(x=1:1225,y=rowSums(C),col="blue")

plot(x=1:1225,y=rowSums(H1),type="l",xlab="date",ylab="#cases",main='Number of cases',col="red")
lines(x=1:1225,y=rowSums(H),col="blue")
```

