---
title: "new paraset"
output: html_document
---
```{r}
###########################################
# 1/duration of maternal immunity (DAYS)
DurationMatImmunityDays= 112
###########################################

###########################################
# update LRI and hospitalization probability
###########################################
al=21
delta1=c(rep(.40,3),rep(.39,3), rep(.21,3),rep(.20,3),0.16,rep(.14,3),rep(0.05,al-16))#proportion of first infections that are LRI (by age)
delta2=.5*delta1#proportion of second infectious that are LRI 
delta3=.7*delta2#proportion of third infections that are LRI
hosp1=c(.18*rep(.40,3),0.08*rep(.39,3),0.07*rep(.21,3),0.06*rep(.20,3),0.06*0.16,0.05*rep(.14,3),0.02*rep(0.05,al-16))#proportion of first LRIs that are hospitalized
hosp2=.4*hosp1#proportion of second LRIs that are hospitalized
hosp3=c(rep(0,al-2),0.00001,0.00004)#proportion of third LRIs that are hospitalized

```

## Run the model 
Note here we are just simulating with set parameters, not fitting to data (check basic population growth and seasonal waves)
```{r}
parms<-list(PerCapitaBirthsYear=PerCapitaBirthsYear,
            DurationMatImmunityDays=DurationMatImmunityDays,
            WidthAgeClassMonth=WidthAgeClassMonth,
            um=um,
            b1=b1,
            phi=phi,
            rho1=rho1,
            rho2=rho2,
            dur.days1=dur.days1,
            dur.days2=dur.days2,
            dur.days3=dur.days3,
            yinit.matrix=yinit.matrix,
            baseline.txn.rate = baseline.txn.rate,
            q=q,
            c=c2,
            sigma1=sigma1,
            sigma2=sigma2,
            sigma3=sigma3,
            time.step='month'
            )

results <- ode(y=yinit.vector, t=my_times,  
               func=simple_model, 
            parms=parms )

## Extract the relevant results
burnN <- 20*12
results.burned <- results[-c(1:burnN),]

##Any infected person
infected.cols <- results.burned[,c(grep('I1', colnames(results.burned)),grep('I2', colnames(results.burned)),grep('I3', colnames(results.burned)),grep('I4', colnames(results.burned)  )) ]

infected.all <- apply(infected.cols,1, sum)

infected.cols.m <- melt(infected.cols)
infected.cols.m$agegrp <- sub(" .*", "",infected.cols.m$Var2 )
infected.cols.c <- dcast(infected.cols.m, Var1~agegrp, fun.aggregate = sum)

#Pop
all.m <- melt(results.burned[,grep('Agegrp',colnames(results.burned))])
all.m$agegrp <- sub(" .*", "",all.m$Var2 )
all.c <- dcast(all.m, Var1~agegrp, fun.aggregate = sum)
pop.all <- apply(all.c[,-1],1,sum)

plot(infected.all, type='l')
plot(pop.all,type="l")

```

## Fit the model
```{r}
parmset<-list(PerCapitaBirthsYear=PerCapitaBirthsYear,
            #DurationMatImmunityDays=DurationMatImmunityDays,
            WidthAgeClassMonth=WidthAgeClassMonth,
            um=um,
            #b1=b1,
            #phi=phi,
            rho1=rho1,
            rho2=rho2,
            dur.days1=dur.days1,
            dur.days2=dur.days2,
            dur.days3=dur.days3,
            yinit.matrix=yinit.matrix,
            #baseline.txn.rate = baseline.txn.rate,
            q=q,
            c=c2,
            sigma1=sigma1,
            sigma2=sigma2,
            sigma3=sigma3,
            time.step='month'
            )

infantrr <-  function(parameters,dat) {   # takes the parameter values and dataset as inputs
  protrans <- parameters[1] # estimate parameter related to R0 (baseline transmission rate)
  amp <- parameters[2] # estimate parameter related to seasonal amplitude
  trans <- parameters[3] # estimate parameter related to seasonal peak timing
  DMD <- parameters[4] # estimate parameter related to the duration of maternal immunity
  b1 <- exp(amp) #ensure positive 
  baseline.txn.rate <- exp(protrans) #ensure positive
  phi <-  (2*pi*(exp(trans))) / (1+exp(trans)) # transform to its scale in the model
  durx <- exp(DMD) #ensure positive
  durx <<- durx #somehow we need this for the function and model to recognize these parameters
  baseline.txn.rate <<- baseline.txn.rate
  b1 <<- b1
  phi <<- phi

   # Simulate the model with initial conditions and timesteps defined above, and parameter values from function call
  results <- ode(y=yinit.vector, t=my_times,  
               func=simple_model, 
            parms=c(parmset,baseline.txn.rate=baseline.txn.rate,b1,phi,DurationMatImmunityDays=durx))
  
  results<- tail(results,t0)
  St <- results[,-1]
   
   b=baseline.txn.rate/(parms$dur.days1/30.44)
   beta=(b/100)/(sum(yinitmatrix)^(1-1))*c2
 
   lambda1=matrix(0,nrow=t0,ncol=al)#Force of infection
    for (t in 1:t0)
    {lambda1[t,] <- as.vector((1+b1*cos(2*pi*(t-phi*12)/12))*((St[t,(2*al+1):(3*al)]+rho1*St[t,(4*al+1):(5*al)]+rho2*St[t,(6*al+1):(7*al)]+rho2*St[t,(8*al+1):(9*al)])%*%beta)/sum(St[t,]))}

  
  H1=matrix(0,nrow=t0,ncol=al)#Number of hospitalizations by age
  for (i in 1:al){
    H1[,i]=hosp1[i]*St[,(al+i)]*lambda1[,i]+hosp2[i]*sigma1*St[,(3*al+i)]*lambda1[,i]+hosp3[i]*sigma2*St[,(5*al+i)]*lambda1[,i]+hosp3[i]*sigma3*St[,(7*al+i)]*lambda1[,i]
    }
  H <- rowSums(H1)

  #age distribution
  agedata1 <- matrix(0,nrow =t0 ,ncol =13 )
  agedata1[,1] <- rowSums(H1[, 1:3])
  agedata1[,2] <- rowSums(H1[, 4:6])
  agedata1[,3] <- rowSums(H1[, 7:9])
  agedata1[,4] <- rowSums(H1[, 10:12])
  agedata1[,5:13] <- H1[, 13:21]
   
   LLall <- sum(dpois(x = dat$rsv, lambda =H, log = TRUE)) # fit to timeseries
   LLmulti <- dmultinom(x= colSums(agedata1),prob = agedistNJ,log = T) # fit to age distribution
   
   #prior
   durprior <- dgamma(x=durx,22,5,log=T)
   
   #total LL
   LL <- LLall+LLmulti+durprior
   
   return(LL)
}

sceLL <- optim(par = c(2.2, -1.630306, -1.299927,  4.365412),           # starting values for beta and gamma - you should get the same result no matter which values you choose here
      fn = infantrr,        # the distance function to optimise
      dat = rsv_month,         # the dataset to fit to ("dat" argument is passed to the function specified in fn)
      control = list(fnscale=-1)) # the log likelihood is negative; here we maximaze the log likelihood
```

### Refit model with estimated parameters
```{r,eval=F}
  baseline.txn.rate=exp(sceLL$par[1])
  b1=exp(sceLL$par[2])
  phi=(2*pi*(exp(sceLL$par[3]))) / (1+exp(sceLL$par[3]))

  output <- ode(y=yinit.vector, t=my_times,  
               func=simple_model, 
            parms=c(parmset,baseline.txn.rate,b1,phi,DurationMatImmunityDays=112))
   
   output <- tail(output,t0)
   St <- output[,-1]
   
   b= baseline.txn.rate/(parms$dur.days1/30.44)
   q=1#exp(maxLL$par[1])/dur
   beta=(b/100)/(sum(N0state)^(1-q))*c2
 
   lambda1=matrix(0,nrow=t0,ncol=al)#Force of infection
    for (t in 1:t0)
    {lambda1[t,] <- as.vector((1+b1*cos(2*pi*(t-phi*12)/12))*((St[t,(2*al+1):(3*al)]+rho1*St[t,(4*al+1):(5*al)]+rho2*St[t,(6*al+1):(7*al)]+rho2*St[t,(8*al+1):(9*al)])%*%beta)/sum(St[t,]))}

   
   H1=matrix(0,nrow=t0,ncol=al)#Number of hospitalizations by age
   for (i in 1:al){
     H1[,i]=hosp1[i]*St[,(al+i)]*lambda1[,i]+hosp2[i]*sigma1*St[,(3*al+i)]*lambda1[,i]+hosp3[i]*sigma2*St[,(5*al+i)]*lambda1[,i]+hosp3[i]*sigma3*St[,(7*al+i)]*lambda1[,i]
   }
   H <- rowSums(H1)
   H <- data.frame(H)
   H$date <- rsv_month$amonthdate
```

## Real Data vs Model Fit
### time series
```{r}
plot(rsv_month$amonthdate,rsv_month$rsv,xlab = "date",ylab="RSV cases",type="l")
lines(H$date,H$H,col="red")
```
### Age distribution
```{r}
 # library
library(ggplot2)
library(tidyr)
 
#Age distribution of hospitalized cases
agedata1 <- matrix(0,nrow =t0 ,ncol =13 )
  agedata1[,1] <- rowSums(H1[, 1:3])
  agedata1[,2] <- rowSums(H1[, 4:6])
  agedata1[,3] <- rowSums(H1[, 7:9])
  agedata1[,4] <- rowSums(H1[, 10:12])
  agedata1[,5:13] <- H1[, 13:21]

agedist1=colSums(agedata1)/sum(colSums(H1[,1:21])) #Summary age distribution of hospitalized cases
agedist1 <- t(matrix(agedist1))
colnames(agedist1) <-  c("0-2m","3-5m","6-8m","9-11m","1yr","2yr","3yr","4yr","5-9","10-19","20-39","40-59","60+")

# create a dataset
agedist <- rbind(agedist1,agedistNJ)
agedist <- data.frame(matrix(agedist,ncol=2,nrow=13,byrow = T))
colnames(agedist) <- c("data","model")
agedist$age <- c(1,2,3,4,5,6,7,8,9,10,11,12,13)

data_long <- gather(agedist, group, proportion,data: model, factor_key=TRUE)

 
# Grouped
ggplot(data_long, aes(fill=group, y=proportion, x=age)) + 
    geom_bar(position="dodge", stat="identity")+
  scale_x_discrete(name ="AGE", 
                    limits=c("0-2m","3-5m","6-8m","9-11m","1yr","2yr","3yr","4yr","5-9","10-19","20-39","40-59","60+"))+
  theme_classic()
```



