---
title: "EffectivenessUncertainty"
author: "Zhe Zheng"
date: "11/21/2021"
output: html_document
---

```{r}
library(rstan)
library(data.table)
library(scales)
## read in stan sample data
csvfiles <- dir(path="",pattern=,full.names = T)
fit1 <- read_stan_csv(csvfiles)
uncertaintysamples <- data.frame(beta=c(fit1@sim$samples[[1]]$beta,fit1@sim$samples[[2]]$beta,fit1@sim$samples[[3]]$beta,fit1@sim$samples[[4]]$beta),b1=c(fit1@sim$samples[[1]]$b1,fit1@sim$samples[[2]]$b1,fit1@sim$samples[[3]]$b1,fit1@sim$samples[[4]]$b1),phi=c(fit1@sim$samples[[1]]$phi,fit1@sim$samples[[2]]$phi,fit1@sim$samples[[3]]$phi,fit1@sim$samples[[4]]$phi),omega=c(fit1@sim$samples[[1]]$omega,fit1@sim$samples[[2]]$omega,fit1@sim$samples[[3]]$omega,fit1@sim$samples[[4]]$omega),hosp_ratio=c(fit1@sim$samples[[1]]$hosp_ratio,fit1@sim$samples[[2]]$hosp_ratio,fit1@sim$samples[[3]]$hosp_ratio,fit1@sim$samples[[4]]$hosp_ratio))
```


```{r}
# Run model 1000 times with different parameter estimates 
nsim <- 100

# set a dataframe 
Mat_output <-as.data.frame(array(dim=c(nsim,108)))
parametertrack <- as.data.frame(array(dim=c(nsim,9)))
Vac_number <- c()

my_times <- seq(1, 408, by = 1) # gives a sequence from start to end

for(j in 1:100){
  
  #sample from distributions of uncertain parameters
  samplevalue <- uncertaintysamples[sample(nrow(uncertaintysamples),1), ]
  baseline.txn.rate=as.numeric(samplevalue["beta"])
  b1=as.numeric(samplevalue["b1"])
  phi=as.numeric(samplevalue["phi"])
  omega=as.numeric(samplevalue["omega"])
  hosp_ratio=as.numeric(samplevalue["hosp_ratio"])
  
  relative_risk <- runif(1,.055,.36)
  Dur_MAbs_inv <- runif(1,0.01691111,0.1106909)
  immunogenic <- runif(1,0.8,1)
  coverage <- runif(1,0.5,1)
  
  parametertrack[j,] <- c(samplevalue,relative_risk,Dur_MAbs,immunogenic,coverage)
  
  parms_mat_dynamic<-list(PerCapitaBirthsYear=Birth_rate[,1:13],
             DurationMatImmunityDays=1/omega*30.44,
            ProPort=c(rep(0,252),rep(coverage,408-252)),
            RR=c(rep(1,252),rep(relative_risk,408-252)), # [0.5, 0.2] 0.3
            WidthAgeClassMonth=1/data_nj$u,
            um=0.00009,
            rho1=0.75,
            rho2=0.51,
            dur.days1=10,
            dur.days2=7,
            dur.days3=5,
            yinit.matrix= yinit.matrix,
            q=1,
            sigma1=0.76,
            sigma2=0.6,
            sigma3=0.4,
            time.step='month',
            c2=matrix(data_nj$c2,nrow = 13,ncol = 13),
            b1=b1,
            phi=phi,
            baseline.txn.rate = baseline.txn.rate
            )
  
  results <- ode(y=yinit.vector, t=my_times,  
               func=maternal_dynamic, 
            parms=parms_mat_dynamic)
  
  
  
  RR=parms_mat_dynamic$RR
   St <- results[,-1]
   q=1
   beta= parms_mat_dynamic$baseline.txn.rate/(sum(yinit.matrix)^(1-q))*parms_mat_dynamic$c2
   t0=408
   al=nrow(yinit.matrix)
   lambda1=matrix(0,nrow=t0,ncol=al)#Force of infection
   Vac_each_month <- rep(0,t0)
    for (t in 1:t0)
    {lambda1[t,] <- as.vector((1+parms_mat_dynamic$b1*cos(2*pi*(t-parms_mat_dynamic$phi*12)/12))*((St[t,(4*al+1):(5*al)]+parms_mat_dynamic$rho1*St[t,(6*al+1):(7*al)]+parms_mat_dynamic$rho2*St[t,(8*al+1):(9*al)]+parms_mat_dynamic$rho2*St[t,(11*al+1):(12*al)]+parms_mat_dynamic$rho2*St[t,(12*al+1):(13*al)])%*%beta)/sum(St[t,]))
    
    Vac_each_month[t] <- parms_mat_dynamic$ProPort[t]*log(Birth_rate[t,1]+1)/12*sum(St[t,])
    }

   hosp1 <- data_nj$hosp1
   hosp2 <- data_nj$hosp2
   hosp3 <- hosp_ratio*hosp2
   
   H1=matrix(0,nrow=t0,ncol=al)#Number of hospitalizations by age
   for (i in 1:al){
     H1[,i]=hosp1[i]*St[,(3*al+i)]*lambda1[,i]+hosp1[i]*St[,(2*al+i)]*RR*lambda1[,i]+hosp2[i]*parms_mat_dynamic$sigma1*St[,(5*al+i)]*lambda1[,i]+hosp3[i]*parms_mat_dynamic$sigma2*St[,(7*al+i)]*lambda1[,i]+hosp3[i]*parms_mat_dynamic$sigma3*St[,(9*al+i)]*lambda1[,i]+hosp3[i]*parms_mat_dynamic$sigma3*St[,(10*al+i)]*lambda1[,i]
   }
   H <- rowSums(H1[,c(1:7)])
   H <- H[241:(241+107)]# the first 12 months was to make sure that different model produce the same baseline cases
   
   Vac_number[j] <- sum(Vac_each_month[241:(241+107)])
   
   Mat_output[j,] <-H
   print(j)
}
  
```

```{r}
MAb_output <-as.data.frame(array(dim=c(nsim,108)))

for(j in 1:100){
  baseline.txn.rate=parametertrack[j,1]
  b1=parametertrack[j,2]
  phi=parametertrack[j,3]
  omega=parametertrack[j,4]
  hosp_ratio=parametertrack[j,5]
  
  relative_risk <- parametertrack[j,6]
  Dur_MAbs <- parametertrack[j,7]
  immunogenic <- parametertrack[j,8]
  coverage <- parametertrack[j,9]
  
  parms_MAb_Dynamics<-list(PerCapitaBirthsYear=Birth_rate[,1:13],
             DurationMatImmunityDays=1/omega*30.44,
            DurationNirImmunityDays=Dur_MAbs,#lower bound 335/upper bound 2200 ( 51.6%-90.2% )??628 70.0% / 908 78.0%
            VacPro=vaccine_administered,
            cover=coverage,
            WidthAgeClassMonth=1/data_nj$u,
            um=0.00009,
            rho1=0.75,
            rho2=0.51,
            dur.days1=10,
            dur.days2=7,
            dur.days3=5,
            yinit.matrix= yinit.matrix,
            q=1,
            sigma1=0.76,
            sigma2=0.6,
            sigma3=0.4,
            time.step='month',
            c2=matrix(data_nj$c2,nrow = 13,ncol = 13),
            b1=b1,
            phi=phi,
            baseline.txn.rate = baseline.txn.rate
            )

results <- ode(y=yinit.vector, t=my_times,  
               func=Mono_dynamics, 
            parms=parms_MAb_Dynamics)
  
St <- results[,-1]
   q=1
   c2=parms_MAb_Dynamics$c2
   beta= parms_MAb_Dynamics$baseline.txn.rate/(sum(yinit.matrix)^(1-q))*c2
   b1= parms_MAb_Dynamics$b1
   phi=parms_MAb_Dynamics$phi
   rho1=parms_MAb_Dynamics$rho1
   rho2=parms_MAb_Dynamics$rho2
   sigma1=parms_MAb_Dynamics$sigma1
   sigma2=parms_MAb_Dynamics$sigma2
   sigma3=parms_MAb_Dynamics$sigma3
   t0=408
   lambda1=matrix(0,nrow=t0,ncol=al)#Force of infection
    for (t in 1:t0)
    {lambda1[t,] <- as.vector((1+b1*cos(2*pi*(t-phi*12)/12))*((St[t,(3*al+1):(4*al)]+rho1*St[t,(5*al+1):(6*al)]+rho2*St[t,(7*al+1):(8*al)]+rho2*St[t,(9*al+1):(10*al)])%*%beta)/sum(St[t,]))}

   hosp1 <- data_nj$hosp1
   hosp2 <- data_nj$hosp2
   hosp3 <- hosp_ratio*hosp2
   
   H1=matrix(0,nrow=t0,ncol=al)#Number of hospitalizations by age
   for (i in 1:al){
     H1[,i]=hosp1[i]*St[,(2*al+i)]*lambda1[,i]+hosp2[i]*sigma1*St[,(4*al+i)]*lambda1[,i]+hosp3[i]*sigma2*St[,(6*al+i)]*lambda1[,i]+hosp3[i]*sigma3*St[,(8*al+i)]*lambda1[,i]
   }
   H <- rowSums(H1[,c(1:7)])
   H <- H[241:(241+107)]
   
   MAb_output[j,] <-H
   print(j)

}
```

```{r}
livevac_output <-as.data.frame(array(dim=c(nsim,108)))

for(j in 1:100){
  baseline.txn.rate=parametertrack[j,1]
  b1=parametertrack[j,2]
  phi=parametertrack[j,3]
  omega=parametertrack[j,4]
  hosp_ratio=parametertrack[j,5]
  
  relative_risk <- parametertrack[j,6]
  Dur_MAbs <- parametertrack[j,7]
  immunogenic <- parametertrack[j,8]
  coverage <- parametertrack[j,9]
  
 parms_livevac_dynamics<-list(PerCapitaBirthsYear=Birth_rate[,1:13],
            DurationMatImmunityDays=1/omega*30.44,
            WidthAgeClassMonth=1/data_nj$u,
            um=0.00009,
            rho1=0.75,
            rho2=0.51,
            burnin=252,
            Cfs=coverage,
            Vfs=immunogenic,
            dur.days1=10,
            dur.days2=7,
            dur.days3=5,
            dur.days_v=5,
            yinit.matrix= yinit.matrix,
            RR=0.85,
            q=1,
            sigma1=0.76,
            sigma2=0.6,
            sigma3=0.4,
            time.step='month',
            c2=matrix(data_nj$c2,nrow = 13,ncol = 13),
            b1=b1,
            phi=phi,
            baseline.txn.rate = baseline.txn.rate
            )

results <- ode(y=yinit.vector, t=my_times,  
               func=livevac_dynamics, 
            parms=parms_livevac_dynamics)
   
   St <- results[,-1]
   q=1
   c2=parms_livevac_dynamics$c2
   beta= parms_livevac_dynamics$baseline.txn.rate/(sum(yinit.matrix)^(1-q))*c2
   b1= parms_livevac_dynamics$b1
   phi=parms_livevac_dynamics$phi
   rho1=parms_livevac_dynamics$rho1
   rho2=parms_livevac_dynamics$rho2
   sigma1=parms_livevac_dynamics$sigma1
   sigma2=parms_livevac_dynamics$sigma2
   sigma3=parms_livevac_dynamics$sigma3
   t0=408
   I1 <- results[,grep('I1', colnames(results))]
   I2 <- results[,grep('I2', colnames(results))]
   I3 <- results[,grep('I3', colnames(results))]
   I4 <- results[,grep('I4', colnames(results))]
   Iv <- results[,grep('Iv', colnames(results))]
   S1 <- results[,grep('S1', colnames(results))]
   S2 <- results[,grep('S2', colnames(results))]
   S3 <- results[,grep('S3', colnames(results))]
   S0 <- results[,grep('S0', colnames(results))]
   Sv <- results[,grep('Sv', colnames(results))]
   lambda1=matrix(0,nrow=t0,ncol=al)#Force of infection
    for (t in 1:t0)
    {lambda1[t,] <- as.vector((1+b1*cos(2*pi*(t-phi*12)/12))*((I1[t,]+rho1*I2[t,]+rho2*I3[t,]+rho2*I4[t,])%*%beta)/sum(St[t,]))}

   hosp1 <- data_nj$hosp1
   hosp2 <- data_nj$hosp2
   hosp3 <- hosp_ratio*hosp2
   
   H1=matrix(0,nrow=t0,ncol=al)#Number of hospitalizations by age
   for (i in 1:al){
     H1[,i]=hosp1[i]*S0[,i]*lambda1[,i]+hosp2[i]*sigma1*S1[,i]*lambda1[,i]+hosp3[i]*sigma2*S2[,i]*lambda1[,i]+hosp3[i]*sigma3*S3[,i]*lambda1[,i]+hosp2[i]*sigma1*lambda1[,i]*Sv[,i]
   }
   
   H <- rowSums(H1[,c(1:7)])
   H <- H[241:(241+107)]
   
   outputArray[j,] <-H
   print(j)
}
```

```{r}
names(outputArray) <- seq(1:ncol(outputArray))
outputArray$iteration <- seq(1:nrow(outputArray))
effectiveness_pred <- reshape2::melt(outputArray, id.vars = c("iteration"), variable.name = "months")
effectiveness_pred <- effectiveness_pred[order(effectiveness_pred$iteration),]
  
ggplot(effectiveness_pred, aes(x = months, y =value,group=iteration)) +
  geom_line( color = "orange",linetype="solid",alpha=0.2,size=0.5) + 
  labs(x = "Day", y = "Number of RSV Hospitalizations")+
  geom_vline(xintercept = 12,linetype="dashed", 
                color = "blue")+
  annotate("text",x=25,y=700,label="Vaccination begin",
                color = "blue")+
     scale_x_discrete("months",breaks = seq(1,108,3))+
  theme_classic()
```

## hospitalizations without vaccines
```{r}
Novac_Hosp <-as.data.frame(array(dim=c(nsim,108)))

yinit.matrix= matrix(data_nj$y0,nrow=13,ncol=9)
dimnames(yinit.matrix)[[2]] <-c('M','S0','I1','S1','I2','S2','I3','S3','I4')
dimnames(yinit.matrix)[[1]] <-c("<2m","2-3m","4-5m","6-7m","8-9m","10-11m","1Y","2-4Y","5-9Y","10-19Y","20-39Y","40-59Y","60Y+")
yinit.vector <- as.vector(yinit.matrix) #Vectorize the ynit matrix
name.array <- array(NA, dim=dim(yinit.matrix))
for(i in 1:dim(name.array)[1]){
  for(j in 1:dim(name.array)[2]){
      name.array[i,j] <- paste(dimnames(yinit.matrix)[[1]][i],dimnames(yinit.matrix)[[2]][j]  )
    }
}

name.vector <- as.vector(name.array)
names(yinit.vector) <- name.vector

Novac_dynamics <-  function(t,y,parms, time.step='month'){
  
  States<-array(y, dim=dim(parms$yinit.matrix))
  dimnames(States) <- dimnames(parms$yinit.matrix)
  um=parms$um
  
  if(parms$time.step=='month'){
    period=12
    length.step=30.44 #days
  }else if(parms$time.step=='week'){
    period=52.1775 
    length.step=7 #days
  }
  
  omega = 1/(parms$DurationMatImmunityDays/length.step)
  
  mu= 1/parms$WidthAgeClassMonth
  if(parms$time.step=='week'){
    mu= 1/(WidthAgeClassMonth*4.345)
  }
  
  gamma1= 1/(parms$dur.days1/length.step)  #converts 1/days to 1/lenth.step
  gamma2= 1/(parms$dur.days2/length.step)  
  gamma3= 1/(parms$dur.days3/length.step)  
  gamma4= gamma3  #??Is this right?? Yes, gamma3 stands for rate of recovery from subsequent infection
  
  #Pull out the states  for the model as vectors
  M <-  States[,'M']
  S0 <-  States[,'S0']
  I1 <-  States[,'I1']
  
  S1 <-  States[,'S1']
  I2 <-  States[,'I2']
  
  S2 <-  States[,'S2']
  I3 <-  States[,'I3']
  
  S3 <-  States[,'S3']
  I4 <-  States[,'I4']
  
  N.ages <- length(M)
  
  ####################
  seasonal.txn <- (1+parms$b1*cos(2*pi*(t-parms$phi*period)/period))# seasonality waves

  beta <-  parms$baseline.txn.rate/(sum(parms$yinit.matrix)^(1-parms$q))*parms$c2# q depends on transmission type (whether depends on population density or not); c2 is the contact matrix
  
  beta_a_i <- seasonal.txn * beta/sum(States)
  infectiousN <- I1 + parms$rho1*I2 + parms$rho2*I3 + parms$rho2*I4
  
  lambda <- infectiousN %*% beta_a_i 
  lambda <- as.vector(lambda)
  ##########transmission dynamics##########################  
  
  dy <- matrix(NA, nrow=N.ages, ncol=ncol(States))
  colnames(dy) <- colnames(States)
  
  period.birth.rate <- log(parms$PerCapitaBirthsYear[t,]+1)/period #B=annual birth rate
  
  #https://journals.plos.org/plospathogens/article/file?id=10.1371/journal.ppat.1004591.s016&type=supplementary
  #mu represents aging to the next class
  #um is death rate/emigration; adjust it to reproduce population growth
  
  Aging.Prop <- c(0,mu[1:(N.ages-1)])
  
  dy[,'M'] <- period.birth.rate*sum(States) - 
    (omega+(mu+um))*M +
    Aging.Prop*c(0,M[1:(N.ages-1)]) 
 
  dy[,'S0'] <- omega*M -
    lambda*S0 - 
    (mu + um)*S0 + 
   Aging.Prop*c(0,S0[1:(N.ages-1)])
  
  dy[,'I1'] <-   lambda*S0 - 
    (gamma1 + mu + um)*I1 + 
    Aging.Prop*c(0,I1[1:(N.ages-1)]) 
  
  dy[,'S1'] <- gamma1*I1 - 
    parms$sigma1*lambda*S1 - 
    (mu+um)*S1 + 
    Aging.Prop*c(0,S1[1:(N.ages-1)]) 
  
  dy[,'I2'] <- parms$sigma1*lambda*S1 - 
    gamma2*I2-(mu + um)*I2 + 
    Aging.Prop*c(0,I2[1:(N.ages-1)]) 
  
  dy[,'S2'] <- gamma2*I2 - 
    parms$sigma2*lambda*S2 -
    (mu+um)*S2 + 
    Aging.Prop*c(0,S2[1:(N.ages-1)]) 
  
  dy[,'I3'] <- parms$sigma2*lambda*S2 -
    (gamma3 + mu+um)*I3 +  
    Aging.Prop*c(0,I3[1:(N.ages-1)]) 
  
  dy[,'S3'] <- gamma3*I3 +  
    gamma4*I4 -
    parms$sigma3*lambda*S3 -
    (mu + um)*S3 + 
    Aging.Prop*c(0,S3[1:(N.ages-1)]) 
  
  dy[,'I4'] <- parms$sigma3*lambda*S3 - 
    gamma4*I4 - 
    (mu + um)*I4 + 
    Aging.Prop*c(0,I4[1:(N.ages-1)]) 
  
  derivs <- as.vector(dy)
  
  res <- list(derivs)
  
  return(res)
}


for(j in 1:100){
  baseline.txn.rate=parametertrack[j,1]
  b1=parametertrack[j,2]
  phi=parametertrack[j,3]
  omega=parametertrack[j,4]
  hosp_ratio=parametertrack[j,5]
  
  parms_novac_Dynamics<-list(PerCapitaBirthsYear=Birth_rate[,1:13],
            DurationMatImmunityDays=1/omega*30.44,
            WidthAgeClassMonth=1/data_nj$u,
            um=0.00009,
            rho1=0.75,
            rho2=0.51,
            dur.days1=10,
            dur.days2=7,
            dur.days3=5,
            yinit.matrix= yinit.matrix,
            q=1,
            sigma1=0.76,
            sigma2=0.6,
            sigma3=0.4,
            time.step='month',
            c2=matrix(data_nj$c2,nrow = 13,ncol = 13),
            b1=b1,
            phi=phi,
            baseline.txn.rate = baseline.txn.rate
            )

results <- ode(y=yinit.vector, t=my_times,  
               func=Novac_dynamics, 
            parms=parms_novac_Dynamics)
  
   St <- results[,-1]
   q=1
   c2=parms_MAb_Dynamics$c2
   baseline.txn.rate=parms_MAb_Dynamics$baseline.txn.rate
   beta= baseline.txn.rate/(sum(yinit.matrix)^(1-q))*c2
   b1= parms_MAb_Dynamics$b1
   phi=parms_MAb_Dynamics$phi
   rho1=parms_MAb_Dynamics$rho1
   rho2=parms_MAb_Dynamics$rho2
   sigma1=parms_MAb_Dynamics$sigma1
   sigma2=parms_MAb_Dynamics$sigma2
   sigma3=parms_MAb_Dynamics$sigma3
    t0=408
   I1 <- results[,grep('I1', colnames(results))]
   I2 <- results[,grep('I2', colnames(results))]
   I3 <- results[,grep('I3', colnames(results))]
   I4 <- results[,grep('I4', colnames(results))]
   S1 <- results[,grep('S1', colnames(results))]
   S2 <- results[,grep('S2', colnames(results))]
   S3 <- results[,grep('S3', colnames(results))]
   S0 <- results[,grep('S0', colnames(results))]
   lambda1=matrix(0,nrow=t0,ncol=al)#Force of infection
    for (t in 1:t0)
    {lambda1[t,] <- as.vector((1+b1*cos(2*pi*(t-phi*12)/12))*((I1[t,]+rho1*I2[t,]+rho2*I3[t,]+rho2*I4[t,])%*%beta)/sum(St[t,]))}

   hosp1 <- data_nj$hosp1
   hosp2 <- data_nj$hosp2
   hosp3 <- hosp_ratio*hosp2
   
   H1=matrix(0,nrow=t0,ncol=al)#Number of hospitalizations by age
   for (i in 1:al){
     H1[,i]=hosp1[i]*S0[,i]*lambda1[,i]+hosp2[i]*sigma1*S1[,i]*lambda1[,i]+hosp3[i]*sigma2*S2[,i]*lambda1[,i]+hosp3[i]*sigma3*S3[,i]*lambda1[,i]
   }
   
   H <- rowSums(H1[,c(1:7)])
   H <- H[241:(241+107)]
   
   Novac_Hosp[j,] <-H
   print(j)  
  }
```

## per-dose effectiveness
```{r}
# (#hosp without vac- #hosp with vac)/ # vac

# first check hospitalizations before vaccine
Novac_Hosp[1,1:12]-outputArray[1,1:12]

Hosp_avert_dose <- rowSums(Novac_Hosp-outputArray)/Vac_number

# compare to other literatures: You Li, Lancet ID 2019
1-rowSums(outputArray[,13:108])/rowSums(Novac_Hosp[,13:108])

```

## random forest 
```{r}
## read in required packages
library(randomForest)
library(datasets)
library(caret)

## create data frame for random forest
rf_df <- data.frame(Hosp_avert_dose=Hosp_avert_dose,beta=parametertrack[,1],b1=parametertrack[,2],phi=parametertrack[,3],omega=parametertrack[,4],hosp_ratio=parametertrack[,5],relative_risk=parametertrack[,6])

set.seed(222)
ind <- sample(2, nrow(rf_df), replace = TRUE, prob = c(0.7, 0.3))
train <- rf_df[ind==1,]
test <- rf_df[ind==2,]

rf <- randomForest(Hosp_avert_dose~., data=rf_df, importance=TRUE)
print(rf)

p2 <- predict(rf, test)
plot(p2,test$Hosp_avert_dose)
abline(a=0,b=1,col="red")

varImpPlot(rf,
           sort = T,
           n.var = 6,
           main = "Top 6 - Variable Importance")
```


