---
title: "MAbs Effectiveness"
author: "Zhe Zheng"
date: "11/15/2021"
output: html_document
---
```{r}
library(deSolve)
library(RColorBrewer)
library(reshape2)
library(tibble)

data_nj <- readRDS("C:/Users/70914/OneDrive/standata/data_msis_NJ_fivepara.rds")
Birth_rate <- readRDS("C:/Users/70914/Box/aim3/RSVtransmissionmodel/RSV_metapop/SimpleModel/data_and_parms/Birth_rate.rds")

hosp1 <- data_nj$hosp1
hosp2 <- data_nj$hosp2
hosp3 <- data_nj$hosp2*0.025 # 0.025 was the best estimate of hospitalization ratio from STAN

# Because different vaccination strategies contains different number of compartments, we need to update the initial matrix 
# for every model structure.
# We fill in the initial matrix with equilibrium dynamics of RSV epidemics
# We started the epidemics with one infectious individuals and a burn-in of 24*12 months to reach the equilibrium status
yinit.matrix= matrix(data_nj$y0,nrow=13,ncol=9)
dimnames(yinit.matrix)[[2]] <-c('M','S0','I1','S1','I2','S2','I3','S3','I4')
dimnames(yinit.matrix)[[1]] <-c("<2m","2-3m","4-5m","6-7m","8-9m","10-11m","1Y","2-4Y","5-9Y","10-19Y","20-39Y","40-59Y","60Y+")
yinit.frame= data.frame(yinit.matrix)
yinit.frame= add_column(yinit.frame,P = rep(0,13), .after = "M")
yinit.matrix=  as.matrix(yinit.frame)
yinit.vector <- as.vector(yinit.matrix) #Vectorize the ynit matrix
name.array <- array(NA, dim=dim(yinit.matrix))
for(i in 1:dim(name.array)[1]){
  for(j in 1:dim(name.array)[2]){
      name.array[i,j] <- paste(dimnames(yinit.matrix)[[1]][i],dimnames(yinit.matrix)[[2]][j]  )
    }
  }

name.vector <- as.vector(name.array)
names(yinit.vector) <- name.vector
```

```{r}
Mono_dynamics <-  function(t,y,parms, time.step='month'){
  
  States<-array(y, dim=dim(parms$yinit.matrix))
  dimnames(States) <- dimnames(parms$yinit.matrix)
  um=parms$um
  
  if(parms$time.step=='month'){
    period=12
    length.step=30.44 #days
  }else if(parms$time.step=='week'){
    period=52.1775 
    length.step=7 #days
  }
  
  omega = 1/(parms$DurationMatImmunityDays/length.step) # waning rate of maternal immunity
  omega_v=1/(parms$DurationNirImmunityDays/length.step) # waning rate of monoclonal antibodies
  Vfs=parms$VacPro[t] #VacPro is a vector, like birthrate data, 1 when vaccine was administrated, 0 otherwise
  Cfs=parms$cover # percent of coverage; between 0-1; should be informed by Pediatric vaccine coverage
  
  
  mu= 1/parms$WidthAgeClassMonth
  if(parms$time.step=='week'){
    mu= 1/(WidthAgeClassMonth*4.345)
  }
  
  gamma1= 1/(parms$dur.days1/length.step)  #converts 1/days to 1/lenth.step
  gamma2= 1/(parms$dur.days2/length.step)  
  gamma3= 1/(parms$dur.days3/length.step)  
  gamma4= gamma3  #??Is this right?? Yes, gamma3 stands for rate of recovery from subsequent infection
  
  #Pull out the states  for the model as vectors
  M <-  States[,'M']
  P <-  States[,'P'] # protected by Monoclonal antibodies
  S0 <-  States[,'S0']
  I1 <-  States[,'I1']
  
  S1 <-  States[,'S1']
  I2 <-  States[,'I2']
  
  S2 <-  States[,'S2']
  I3 <-  States[,'I3']
  
  S3 <-  States[,'S3']
  I4 <-  States[,'I4']
  
  N.ages <- length(M)
  
  ####################
  seasonal.txn <- (1+parms$b1*cos(2*pi*(t-parms$phi*period)/period))# seasonality waves

  beta <-  parms$baseline.txn.rate/(sum(parms$yinit.matrix)^(1-parms$q))*parms$c2# q depends on transmission type (whether depends on population density or not); c2 is the contact matrix
  
  beta_a_i <- seasonal.txn * beta/sum(States)
  infectiousN <- I1 + parms$rho1*I2 + parms$rho2*I3 + parms$rho2*I4
  
  lambda <- infectiousN %*% beta_a_i 
  lambda <- as.vector(lambda)
  ##########transmission dynamics##########################  
  
  dy <- matrix(NA, nrow=N.ages, ncol=ncol(States))
  colnames(dy) <- colnames(States)
  
  period.birth.rate <- log(parms$PerCapitaBirthsYear[t,]+1)/period #B=annual birth rate
  
  #https://journals.plos.org/plospathogens/article/file?id=10.1371/journal.ppat.1004591.s016&type=supplementary
  #mu represents aging to the next class
  #um is death rate/emigration; adjust it to reproduce population growth
  
  Aging.Prop <- c(0,mu[1:(N.ages-1)])
  
  dy[,'M'] <- period.birth.rate*sum(States) - 
    (omega+(mu+um))*M +
    c(1,(1-Vfs*Cfs),1,1,1,1,1,rep(1,6))*Aging.Prop*c(0,M[1:(N.ages-1)]) 
  # When infants reach 2 month of age, they wil be given monoclonal antibodies; 
  # the individuals who do not receive MAbs will stay in M compartment
  
  # P compartment stands for infants that are protected by Monoclonal antibodies
  dy[,'P'] <-  c(0,Vfs*Cfs,0,0,0,0,0,rep(0,6))*Aging.Prop*c(0,M[1:(N.ages-1)]) +
    # Inflow from M compartment
    c(0,Vfs*Cfs,0,0,0,0,0,rep(0,6))*Aging.Prop*c(0,S0[1:(N.ages-1)]) - 
    # Inflow from S0 compartment
    (omega_v+(mu+um))*P +
     # after the immunity wane (waning rate = omega_v), these infants will be susceptible to infections
    # mu stands for death/emigration rate and um stands for aging out
    Aging.Prop*c(0,P[1:(N.ages-1)]) # this is for aging in 
  
  dy[,'S0'] <- omega*M+omega_v*P - # after maternal protection or MAbs protection wane, 
    # infants will be susceptible to infections
    lambda*S0 - # being infected
    (mu + um)*S0 + 
    c(1,(1-Vfs*Cfs),1,1,1,1,1,rep(1,6))*Aging.Prop*c(0,S0[1:(N.ages-1)])
  # When infants reach 2 month of age, they wil be given monoclonal antibodies; 
  # the individuals who do not receive MAbs will stay in S0 compartment
  
  dy[,'I1'] <-   lambda*S0 - 
    (gamma1 + mu + um)*I1 + 
    Aging.Prop*c(0,I1[1:(N.ages-1)]) 
  
  dy[,'S1'] <- gamma1*I1 - 
    parms$sigma1*lambda*S1 - 
    (mu+um)*S1 + 
    Aging.Prop*c(0,S1[1:(N.ages-1)]) 
  
  dy[,'I2'] <- parms$sigma1*lambda*S1 - 
    gamma2*I2-(mu + um)*I2 + 
    Aging.Prop*c(0,I2[1:(N.ages-1)]) 
  
  dy[,'S2'] <- gamma2*I2 - 
    parms$sigma2*lambda*S2 -
    (mu+um)*S2 + 
    Aging.Prop*c(0,S2[1:(N.ages-1)]) 
  
  dy[,'I3'] <- parms$sigma2*lambda*S2 -
    (gamma3 + mu+um)*I3 +  
    Aging.Prop*c(0,I3[1:(N.ages-1)]) 
  
  dy[,'S3'] <- gamma3*I3 +  
    gamma4*I4 -
    parms$sigma3*lambda*S3 -
    (mu + um)*S3 + 
    Aging.Prop*c(0,S3[1:(N.ages-1)]) 
  
  dy[,'I4'] <- parms$sigma3*lambda*S3 - 
    gamma4*I4 - 
    (mu + um)*I4 + 
    Aging.Prop*c(0,I4[1:(N.ages-1)]) 
  
  derivs <- as.vector(dy)
  
  res <- list(derivs)
  
  return(res)
}
```

```{r}
vaccine_administered <- c(rep(0,252),rep(1,408-252)) # MAbs initiate in 21*12 months
```

```{r}
parms_MAb_Dynamics<-list(PerCapitaBirthsYear=Birth_rate[,1:13], # I have 13 age groups instead of 21
             DurationMatImmunityDays=86, # From STAN estimate; duration of maternal immunity
            DurationNirImmunityDays=230, # From efficacy estimate; this is the lower bound
            VacPro=vaccine_administered, # The time that vaccination starts; I keep the first 9 years to compare with
            # real hospitalization data (2005-2014). The vaccination starts in 2026 for this assumption 
            cover=0.6, # can sample from a uncertainty distribution as well to reflect the pediatric vaccine coverage 
            WidthAgeClassMonth=1/data_nj$u, # aging in and out
            um=0.00009, # adjust to represent population growth/decline
            rho1=0.75, 
            rho2=0.51,
            dur.days1=10,
            dur.days2=7,
            dur.days3=5,
            yinit.matrix= yinit.matrix,
            q=1,
            sigma1=0.76,
            sigma2=0.6,
            sigma3=0.4,
            time.step='month',
            c2=matrix(data_nj$c2,nrow = 13,ncol = 13),
            b1=0.198,
            phi=3.338,
            baseline.txn.rate = 7.9
            )

my_times <- seq(1, 408, by = 1) # gives a sequence from start to end

results <- ode(y=yinit.vector, t=my_times,  
               func=Mono_dynamics, 
            parms=parms_MAb_Dynamics)
```


```{r}
   St <- results[,-1]
   q=1
   c2=parms_MAb_Dynamics$c2
   baseline.txn.rate=parms_MAb_Dynamics$baseline.txn.rate
   beta= baseline.txn.rate/(sum(yinit.matrix)^(1-q))*c2
   b1= parms_MAb_Dynamics$b1
   phi=parms_MAb_Dynamics$phi
   rho1=parms_MAb_Dynamics$rho1
   rho2=parms_MAb_Dynamics$rho2
   sigma1=parms_MAb_Dynamics$sigma1
   sigma2=parms_MAb_Dynamics$sigma2
   sigma3=parms_MAb_Dynamics$sigma3
   t0=408
   lambda1=matrix(0,nrow=t0,ncol=al)#Force of infection; lambda= beta*I
    for (t in 1:t0)
    {lambda1[t,] <- as.vector((1+b1*cos(2*pi*(t-phi*12)/12))*((St[t,(3*al+1):(4*al)]+rho1*St[t,(5*al+1):(6*al)]+rho2*St[t,(7*al+1):(8*al)]+rho2*St[t,(9*al+1):(10*al)])%*%beta)/sum(St[t,]))} 

   hosp1 <- data_nj$hosp1
   hosp2 <- data_nj$hosp2
   hosp3 <- data_nj$hosp2*0.025
   
   H1=matrix(0,nrow=t0,ncol=al)#Number of hospitalizations by age; hospitalization ratio*lambda*S
   for (i in 1:al){
     H1[,i]=hosp1[i]*St[,(2*al+i)]*lambda1[,i]+hosp2[i]*sigma1*St[,(4*al+i)]*lambda1[,i]+hosp3[i]*sigma2*St[,(6*al+i)]*lambda1[,i]+hosp3[i]*sigma3*St[,(8*al+i)]*lambda1[,i]
   }
   H <- rowSums(H1[,c(1:7)]) # consider only children under 2 years of age
   H <- data.frame(H)
   
   H_50_twomon <- H$H[241:(241+107)]
```

```{r}
# make sure that the model can reproduce the observed hospitalizations well
plot(data_nj$ts,data_nj$hosp_cases,xlab = "date",ylab="RSV cases",type="l")
lines(data_nj$ts,H$H[1:108],col="red")
```

```{r}
# generate a range of effectiveness (the final version should use uncertainty distribution; please ignore this part)
effectiveness_pred <- as.data.frame(cbind(H_50,H_70,H_90, c(1:108), data_nj$hosp_cases,H_0))
colnames(effectiveness_pred) <- c("50%E","70%E","90%E","t" ,"cases") # to remove % in the col names

ggplot(effectiveness_pred, mapping = aes(x = t)) +
  geom_ribbon(aes(ymin = `50%E`, ymax = `90%E`), fill = "orange", alpha = 0.25) +
  geom_line(mapping = aes(x = t, y =`70%E`), color = "orange",linetype="solid") + 
  #geom_line(mapping = aes(x = t, y =H_0), color = "black",linetype="dotted") +
  labs(x = "Day", y = "Number of RSV Hospitalizations")+
  geom_vline(xintercept = 12,linetype="dashed", 
                color = "blue")+
  annotate("text",x=25,y=700,label="Vaccination begin",
                color = "blue")+
  theme_classic()
```
