---
title: "Mat_Vac_Effective"
author: "Zhe Zheng"
date: "11/15/2021"
output: html_document
---


```{r}
### load required library
library(deSolve) # for ODE function
library(RColorBrewer) # for pretty color in ggplot
library(reshape2) # to reshape data frames from wide to long for plotting
library(tibble) # to add additional columns to the initial matrix
library(ggplot2) # to plot
```

```{r}
# equilibrium status of RSV epidemics in New Jersey using parameter estimates from maximum likelihood estimates
data_nj <- readRDS("C:/Users/70914/OneDrive/standata/data_msis_NJ_fivepara.rds")
# Birth rate from CDC WONDER database
Birth_rate <- readRDS("C:/Users/70914/Box/aim3/RSVtransmissionmodel/RSV_metapop/SimpleModel/data_and_parms/Birth_rate.rds")


hosp1 <- data_nj$hosp1# proportion of first infections that are hospitalized
hosp2 <- data_nj$hosp2 # proportion of second infections that are hospitalized
hosp3 <- data_nj$hosp2*0.025 # proportion of third and subsequent infections that are hospitalized

al <- 13 # number of age groups
c2 <- data_nj$c2 # contact matrix
```

```{r saveparms}

# initialize a 13*13 matrix and a vector length 169 that contains 13 age groups and 13 transmission/vaccination compartments
yinit.matrix= matrix(data_nj$y0,nrow=13,ncol=9)
dimnames(yinit.matrix)[[2]] <-c('M','S0','I1','S1','I2','S2','I3','S3','I4')
dimnames(yinit.matrix)[[1]] <-c("<2m","2-3m","4-5m","6-7m","8-9m","10-11m","1Y","2-4Y","5-9Y","10-19Y","20-39Y","40-59Y","60Y+")
yinit.frame= data.frame(yinit.matrix)
# This model assumed that vaccinating pregnant women will provide additional protection to newborns that lower 
# the susceptibility of the newborns when they come into contact with RSV 
yinit.frame= add_column(yinit.frame,Mv = rep(0,13),Sv = rep(0,13), .after = "M")
# Vaccination may also provide additional benefit for the pregnant women as well, which may lower their susceptibility # and infectiousness when they are infected. This may provide indirect benefit to their newborns as well
yinit.frame= add_column(yinit.frame,V1 = rep(0,13),Iv = rep(0,13), .after = "S3")
yinit.matrix=  as.matrix(yinit.frame)
yinit.vector <- as.vector(yinit.matrix) #Vectorize the ynit matrix
name.array <- array(NA, dim=dim(yinit.matrix))
for(i in 1:dim(name.array)[1]){
  for(j in 1:dim(name.array)[2]){
      name.array[i,j] <- paste(dimnames(yinit.matrix)[[1]][i],dimnames(yinit.matrix)[[2]][j]  )
    }
  }

name.vector <- as.vector(name.array)
names(yinit.vector) <- name.vector

```

```{r}
maternal_dynamic <- function(t,y,parms, time.step='month'){
  
  States<-array(y, dim=dim(parms$yinit.matrix))
  dimnames(States) <- dimnames(parms$yinit.matrix)
  um=parms$um
  
  if(parms$time.step=='month'){
    period=12
    length.step=30.44 #days
  }else if(parms$time.step=='week'){
    period=52.1775
    length.step=7 #days
  }
  
  omega = 1/(parms$DurationMatImmunityDays/length.step)
  v=parms$VacPro[t]*parms$cover # indicator function for when the vaccine will be administered * vaccine coverage
  RR=parms$RR[t] # relative risk of infection after vaccination; equal to 1 before vaccine introduction
  
  mu= 1/parms$WidthAgeClassMonth
  if(parms$time.step=='week'){
    mu= 1/(WidthAgeClassMonth*4.345)
  }
  
  gamma1= 1/(parms$dur.days1/length.step)  #converts 1/days to 1/lenth.step
  gamma2= 1/(parms$dur.days2/length.step)  
  gamma3= 1/(parms$dur.days3/length.step)  
  gamma4= gamma3  #??Is this right?? Yes, gamma3 stands for rate of recovery from subsequent infection
  
  #Pull out the states  for the model as vectors
  M <-  States[,'M'] # newborns without vaccination of mothers 
  Mv <-  States[,'Mv'] # newborns with vaccination of mothers 
  Sv <-  States[,'Sv']  # newborns with vaccination of mothers has lower risk of infections when maternal immunity wanes
  S0 <-  States[,'S0']
  I1 <-  States[,'I1']
  
  S1 <-  States[,'S1']
  I2 <-  States[,'I2']
  
  S2 <-  States[,'S2']
  I3 <-  States[,'I3']
  
  S3 <-  States[,'S3']
  I4 <-  States[,'I4']
  
  V1 <-  States[,'V1'] # vaccination of pregnant women
  Iv <-  States[,'Iv'] # infected status of women that ever received vaccines
  
  N.ages <- length(M)
  
  ###Check the standardization of beta and overall structure of lambda here
  ####################
 seasonal.txn <- (1+parms$b1*cos(2*pi*(t-parms$phi*period)/period))# seasonality waves

  beta <-  parms$baseline.txn.rate/(sum(parms$yinit.matrix)^(1-parms$q))*parms$c2# q depends on transmission type (whether depends on population density or not); c2 is the contact matrix
  
  beta_a_i <- seasonal.txn * beta/sum(States)
  infectiousN <- I1 + parms$rho1*I2 + parms$rho2*I3 + parms$rho2*I4+parms$rho2*Iv
  # may change based on how much will the vaccine reduce the infectiousness
  
  lambda <- infectiousN %*% beta_a_i 
  lambda <- as.vector(lambda)
  ##########?????????????????##########################  
  
  dy <- matrix(NA, nrow=N.ages, ncol=ncol(States))
  colnames(dy) <- colnames(States)
  
  period.birth.rate <- log(parms$PerCapitaBirthsYear[t,]+1)/period #B=annual birth rate
  
  #https://journals.plos.org/plospathogens/article/file?id=10.1371/journal.ppat.1004591.s016&type=supplementary
  #mu represents aging to the next class
  #um is death rate
  
  Aging.Prop <- c(0,mu[1:(N.ages-1)])
  
  # newborns without vaccination of mothers is still protected from infections because of maternal immunity
  dy[,'M'] <- (1-v)*period.birth.rate*sum(States) - 
    (omega+(mu+um))*M +
    Aging.Prop*c(0,M[1:(N.ages-1)]) 
  
  # newborns with vaccination of mothers is also protected from infections because of maternal immunity
  dy[,'Mv'] <- v*period.birth.rate*sum(States) - 
    (omega+(mu+um))*Mv +
    Aging.Prop*c(0,Mv[1:(N.ages-1)])
  
  # after the maternal immunity wanes, newborns with vaccination of mothers has lower risk of infections 
  dy[,'Sv'] <- omega*Mv - 
    RR*lambda*Sv -
    (mu + um)*Sv + 
    Aging.Prop*c(0,Sv[1:(N.ages-1)]) 
  
  dy[,'S0'] <- omega*M -
    lambda*S0 -
    (mu + um)*S0 + 
    Aging.Prop*c(0,S0[1:(N.ages-1)]) 
  
  dy[,'I1'] <-   lambda*S0+ RR*lambda*Sv - 
    (gamma1 + mu + um)*I1 + 
    Aging.Prop*c(0,I1[1:(N.ages-1)]) 
  
  dy[,'S1'] <- gamma1*I1 - 
    parms$sigma1*lambda*S1 - 
    (mu+um)*S1 + 
    Aging.Prop*c(0,S1[1:(N.ages-1)]) 
  
  dy[,'I2'] <- parms$sigma1*lambda*S1 - 
    gamma2*I2-(mu + um)*I2 + 
    Aging.Prop*c(0,I2[1:(N.ages-1)]) 
  
  dy[,'S2'] <- gamma2*I2 - 
    parms$sigma2*lambda*S2 -
    (mu+um)*S2 + 
    Aging.Prop*c(0,S2[1:(N.ages-1)]) 
  
  dy[,'I3'] <- parms$sigma2*lambda*S2 -
    (gamma3 + mu+um)*I3 +  
    Aging.Prop*c(0,I3[1:(N.ages-1)]) 
  
  dy[,'S3'] <- gamma3*I3 +  
    gamma4*I4 -
    parms$sigma3*lambda*S3 -
    c(rep(0,10),sum(v*period.birth.rate*sum(States)),rep(0,2)) -
    (mu + um)*S3 + 
    Aging.Prop*c(0,S3[1:(N.ages-1)]) 
  
  # pregnant women (age 20-39) will enter the V1 compartment; the number is equal to newborn (approximately because most of births are single live birth)
  # I did not add any reduced susceptibility or infectiousness at this point and therefore V1 is no different than S3
  dy[,'V1'] <- c(rep(0,10),v*period.birth.rate[1]*sum(States),rep(0,2)) +
    gamma4*Iv-
    parms$sigma3*lambda*V1 -
    (mu + um)*V1 + 
    Aging.Prop*c(0,V1[1:(N.ages-1)]) 
  
  dy[,'I4'] <- parms$sigma3*lambda*S3 - 
    gamma4*I4 - 
    (mu + um)*I4 + 
    Aging.Prop*c(0,I4[1:(N.ages-1)]) 
  
  dy[,'Iv'] <- parms$sigma3*lambda*V1 - 
    gamma4*Iv - 
    (mu + um)*Iv + 
    Aging.Prop*c(0,Iv[1:(N.ages-1)])
  
  derivs <- as.vector(dy)
  
  res <- list(derivs)
  
  return(res)
}
```

```{r}
vaccine_administered <- c(rep(0,252),rep(1,408-252)) # indicator function for when the vaccine will be administered
```

```{r}
# the meaning of other parameters can be seem in MAbsatbirth.RMD 
parms_mat_dynamic<-list(PerCapitaBirthsYear=Birth_rate[,1:13],
             DurationMatImmunityDays=86, # the best estimate from MAP, will change within a range to evaluate its impact
              VacPro=vaccine_administered, # vaccine administer indicator function
            cover=1, # vaccine coverage
            RR=c(rep(1,252),rep(0.36,408-252)), # relative risk of infection; depends on vaccine efficacy
            WidthAgeClassMonth=1/data_nj$u,
            um=0.00009,
            rho1=0.75,
            rho2=0.51,
            dur.days1=10,
            dur.days2=7,
            dur.days3=5,
            yinit.matrix= yinit.matrix,
            q=1,
            sigma1=0.76,
            sigma2=0.6,
            sigma3=0.4,
            time.step='month',
            c2=matrix(data_nj$c2,nrow = 13,ncol = 13),
            b1=0.198,
            phi=3.338,
            baseline.txn.rate = 7.9
            )
```

```{r}
my_times <- seq(1, 408, by = 1) # gives a sequence from start to end

results <- ode(y=yinit.vector, t=my_times,  
               func=maternal_dynamic, 
            parms=parms_mat_dynamic)

```

```{r}
infected.cols <- results[,c(grep('I1', colnames(results)),grep('I2', colnames(results)),grep('I3', colnames(results)),grep('I4', colnames(results)  ),grep('Iv', colnames(results)  )) ]

infected.all <- apply(infected.cols,1, sum)

infected.cols.m <- melt(infected.cols)
infected.cols.m$agegrp <- sub(" .*", "",infected.cols.m$Var2 )
infected.cols.c <- dcast(infected.cols.m, Var1~agegrp, fun.aggregate = sum)

plot(infected.all, type='l')
plot(rowSums(results[,-1]),type="l")

v1 <- results[,grep('20-39Y V1', colnames(results)) ]
Midlleage <- rowSums(results[,grep('20-39Y', colnames(results)) ])
max(v1/Midlleage*100) # check the percentage of population that ever be pregnant
```

```{r}
   
   RR=parms_mat_dynamic$RR
   St <- results[,-1]
   q=1
   beta= parms_mat_dynamic$baseline.txn.rate/(sum(yinit.matrix)^(1-q))*parms_mat_dynamic$c2
   t0=408
   lambda1=matrix(0,nrow=t0,ncol=al)#Force of infection
    for (t in 1:t0)
    {lambda1[t,] <- as.vector((1+parms_mat_dynamic$b1*cos(2*pi*(t-parms_mat_dynamic$phi*12)/12))*((St[t,(4*al+1):(5*al)]+parms_mat_dynamic$rho1*St[t,(6*al+1):(7*al)]+parms_mat_dynamic$rho2*St[t,(8*al+1):(9*al)]+parms_mat_dynamic$rho2*St[t,(11*al+1):(12*al)]+parms_mat_dynamic$rho2*St[t,(12*al+1):(13*al)])%*%beta)/sum(St[t,]))}

   hosp1 <- data_nj$hosp1
   hosp2 <- data_nj$hosp2
   hosp3 <- data_nj$hosp2*0.025
   
   H1=matrix(0,nrow=t0,ncol=al)#Number of hospitalizations by age
   for (i in 1:al){
     H1[,i]=hosp1[i]*St[,(3*al+i)]*lambda1[,i]+hosp1[i]*St[,(2*al+i)]*RR*lambda1[,i]+hosp2[i]*parms_mat_dynamic$sigma1*St[,(5*al+i)]*lambda1[,i]+hosp3[i]*parms_mat_dynamic$sigma2*St[,(7*al+i)]*lambda1[,i]+hosp3[i]*parms_mat_dynamic$sigma3*St[,(9*al+i)]*lambda1[,i]+hosp3[i]*parms_mat_dynamic$sigma3*St[,(10*al+i)]*lambda1[,i]
   }
   H <- rowSums(H1[,c(1:7)])
   H <- data.frame(H)
   
   H_50_reduced_risk <- H$H[241:(241+107)]
```

```{r}
plot(data_nj$ts,data_nj$hosp_cases,xlab = "date",ylab="RSV cases",type="l")
lines(data_nj$ts,H$H[1:108],col="red")

plot(1:108,H_50_reduced_risk,xlab = "date",ylab="RSV Hospitalizations",type="l",main="model structure comparison in children under two",bty="n")
lines(1:108,H_50_duration,col="red",lty = 2)
legend("topright",c("reduced risk","longer duration"),lty=c(1,2),col = c("black","red"),bty="n")
```

```{r}
effectiveness_pred <- as.data.frame(cbind(H_50,H_70,H_90, c(1:108), data_nj$hosp_cases,H_0))
colnames(effectiveness_pred) <- c("50%E","70%E","90%E","t" ,"cases") # to remove % in the col names

ggplot(effectiveness_pred, mapping = aes(x = t)) +
  geom_ribbon(aes(ymin = `50%E`, ymax = `90%E`), fill = "orange", alpha = 0.25) +
  geom_line(mapping = aes(x = t, y =`70%E`), color = "orange",linetype="solid") + 
  #geom_line(mapping = aes(x = t, y =H_0), color = "black",linetype="dotted") +
  labs(x = "Day", y = "Number of RSV Hospitalizations")+
  geom_vline(xintercept = 12,linetype="dashed", 
                color = "blue")+
  annotate("text",x=25,y=700,label="Vaccination begin",
                color = "blue")+
  theme_classic()
```
