---
title: "booster sensitivity"
author: "Zhe Zheng"
date: "2/1/2022"
output: html_document
---

```{r}
## load library and datasets
```


```{r saveparms}
yinit.matrix= matrix(c(data_nj+data_ny+data_ca+data_wa),nrow=13,ncol=9)
dimnames(yinit.matrix)[[2]] <-c('M','S0','I1','S1','I2','S2','I3','S3','I4')
dimnames(yinit.matrix)[[1]] <-c("<2m","2-3m","4-5m","6-7m","8-9m","10-11m","1Y","2-4Y","5-9Y","10-19Y","20-39Y","40-59Y","60Y+")
yinit.frame= data.frame(yinit.matrix)
yinit.frame= add_column(yinit.frame,Iv = rep(0,13), .after = "I1")
yinit.frame= add_column(yinit.frame,V1 = rep(0,13), .after = "Iv")
yinit.frame= add_column(yinit.frame,V2 = rep(0,13), .after = "I2")
yinit.matrix=  as.matrix(yinit.frame)
yinit.vector <- as.vector(yinit.matrix) #Vectorize the ynit matrix
name.array <- array(NA, dim=dim(yinit.matrix))
for(i in 1:dim(name.array)[1]){
  for(j in 1:dim(name.array)[2]){
      name.array[i,j] <- paste(dimnames(yinit.matrix)[[1]][i],dimnames(yinit.matrix)[[2]][j]  )
    }
  }

name.vector <- as.vector(name.array)
names(yinit.vector) <- name.vector

```


```{r}
livevac_booster<- function(t,y,parms, time.step='month'){
  
  States<-array(y, dim=dim(parms$yinit.matrix))
  dimnames(States) <- dimnames(parms$yinit.matrix)
  um=parms$um
  
  if(parms$time.step=='month'){
    period=12
    length.step=30.44 #days
  }else if(parms$time.step=='week'){
    period=52.1775
    length.step=7 #days
  }
  
  omega = 1/(parms$DurationMatImmunityDays/length.step)
  
  mu= 1/parms$WidthAgeClassMonth
  if(parms$time.step=='week'){
    mu= 1/(WidthAgeClassMonth*4.345)
  }
  
  gamma1= 1/(parms$dur.days1/length.step)  #converts 1/days to 1/lenth.step
  gamma2= 1/(parms$dur.days2/length.step)  
  gamma3= 1/(parms$dur.days3/length.step)  
  gamma4= gamma3  #gamma3 stands for rate of recovery from subsequent infection
  gamma_v= 1/(parms$dur.days_v/length.step)
  
   Cfs = parms$Cfs*parms$VacPro[t]  # vaccine coverage will be informed by pediatric vaccine coverage

  
	#read in vaccination efficacy
   Vfs = parms$Vfs
   
  
  #Pull out the states  for the model as vectors
  M <-  States[,'M']
  S0 <-  States[,'S0']
  I1 <-  States[,'I1']
  
  Iv <-  States[,'Iv']
  V1 <-  States[,'V1']
  V2 <-  States[,'V2']
  
  S1 <-  States[,'S1']
  I2 <-  States[,'I2']
  
  S2 <-  States[,'S2']
  I3 <-  States[,'I3']
  
  S3 <-  States[,'S3']
  I4 <-  States[,'I4']
  
  
  N.ages <- length(M)
  

   ##seasonal lambda parameter##################
    seasonal.txn <- (1+parms$b1*cos(2*pi*(t-parms$phi*period)/period))# seasonality waves
  
  # baseline.txn.rate is the probability of transmission given contact per capita
  # (parms$dur.days1/30.44) is the duration of infectiousness of primary infection
  # q depends on transmission type (whether depends on population density or not)
  # density (q=0) vs frequency-dependent (q=1) transmission
  # c2 is the contact matrix 
  # beta is transimissibility per unit time
  transmission_unittime <-  parms$baseline.txn.rate/(parms$dur.days1/length.step)
  beta=transmission_unittime*parms$c2
  
  beta_a_i <- seasonal.txn * beta/(sum(States)^parms$q)
  infectiousN <- I1 + parms$rho1*I2 + parms$rho2*I3 + parms$rho2*I4
  
  lambda <- infectiousN %*% beta_a_i 
  lambda <- as.vector(lambda)
  lambda_v <- Iv%*%beta_a_i*parms$RR  # lambda_v= transmissibility of vaccine virus * number of vaccinated individuals
  # that shed vaccine virus currently
  ##########?????????????????##########################  
  
  dy <- matrix(NA, nrow=N.ages, ncol=ncol(States))
  colnames(dy) <- colnames(States)
  
  period.birth.rate <- log(parms$PerCapitaBirthsYear[t,]+1)/period #B=annual birth rate
  
  #https://journals.plos.org/plospathogens/article/file?id=10.1371/journal.ppat.1004591.s016&type=supplementary
  #mu represents aging to the next class
  #um is death rate
  
  Aging.Prop <- c(0,mu[1:(N.ages-1)])
  
  dy[,'M'] <- period.birth.rate*sum(States) - 
    (omega+(mu+um))*M +
   c(0,M[1:(N.ages-1)])*Aging.Prop -
     c(0,M[1:(N.ages-1)])*c(0,Cfs*Vfs,rep(0,(N.ages-2)))*Aging.Prop

  dy[,'S0'] <- omega*M -
    lambda*S0 -
    (mu + um)*S0 + 
    c(1,(1-Cfs*Vfs),rep(1,N.ages-2))*Aging.Prop*c(0,S0[1:(N.ages-1)]) -
    lambda_v*S0
  
  dy[,'I1'] <-   lambda*S0 - 
    (gamma1 + mu + um)*I1 + 
    Aging.Prop*c(0,I1[1:(N.ages-1)]) 
  
  dy[,'Iv'] <-  c(0,M[1:(N.ages-1)])*c(0,Cfs*Vfs,rep(0,N.ages-2))*Aging.Prop +
     c(0,Cfs*Vfs,rep(0,N.ages-2))*Aging.Prop*c(0,S0[1:(N.ages-1)]) +  
     lambda_v*S0 -
     ( mu + um)*Iv + 
     Aging.Prop*c(0,Iv[1:(N.ages-1)]) - 
     gamma_v*Iv
  
  dy[,'V1'] <-   gamma_v*Iv - 
    parms$sigma1*lambda*V1 -
    (mu+um)*V1 + 
    c(1,1,(1-Cfs*Vfs),rep(1,N.ages-3))*Aging.Prop*c(0,V1[1:(N.ages-1)])
  
  dy[,'S1'] <- gamma1*I1 - 
    parms$sigma1*lambda*S1 - 
    (mu+um)*S1 + 
    Aging.Prop*c(0,S1[1:(N.ages-1)])
  
  dy[,'I2'] <- parms$sigma1*lambda*S1 +
    parms$sigma1*lambda*V1 - 
    gamma2*I2-(mu + um)*I2 + 
    Aging.Prop*c(0,I2[1:(N.ages-1)]) 
  
  dy[,'V2'] <-   c(0,0,Cfs*Vfs,rep(0,N.ages-3))*Aging.Prop*c(0,V1[1:(N.ages-1)])  - 
    parms$sigma2*lambda*V2 -
    (mu+um)*V2 + 
    Aging.Prop*c(0,V2[1:(N.ages-1)])
  
  dy[,'S2'] <- gamma2*I2 - 
    parms$sigma2*lambda*S2 -
    (mu+um)*S2+ 
    Aging.Prop*c(0,S2[1:(N.ages-1)]) 
  
  dy[,'I3'] <- parms$sigma2*lambda*S2 +
    parms$sigma2*lambda*V2 -
    (gamma3 + mu+um)*I3 +  
    Aging.Prop*c(0,I3[1:(N.ages-1)]) 
  
  dy[,'S3'] <- gamma3*I3 +  
    gamma4*I4 -
    parms$sigma3*lambda*S3 -
    (mu + um)*S3 + 
    Aging.Prop*c(0,S3[1:(N.ages-1)])
  
  dy[,'I4'] <- parms$sigma3*lambda*S3 - 
    gamma4*I4 - 
    (mu + um)*I4 + 
    Aging.Prop*c(0,I4[1:(N.ages-1)]) 
  
  
  
  
  derivs <- as.vector(dy)
  
  res <- list(derivs)
  
  return(res)
}

```

```{r}
livevac_output <-array(dim=c(nsim,108,al))
livevac_agedist <-as.data.frame(array(dim=c(nsim,al)))
Doses_livevax <- c()

for(j in 1:nsim){
  immunogenic <- params.set[j,3]
  coverage <- params.set[j,4]
  age_dist <- c()

  baseline.txn.rate=params.set[j,6]
  b1=params.set[j,8]
  phi=params.set[j,7]
  omega=params.set[j,9]
  report_ratio=params.set[j,10]
  
 parms_livevac_dynamics<-list(PerCapitaBirthsYear=as.matrix(birthrate),
            DurationMatImmunityDays=1/omega*30.44,
            WidthAgeClassMonth=1/data_msis$u,
            um=-0.0005,
            rho1=0.75,
            rho2=0.51,
            VacPro=c(rep(0,264),rep(1,444-264)),
             #c(rep(0,264),rep(c(0,0,0,0,1,1,1,1,1,0,0,0),(444-264)/12)),
            Cfs=coverage,
            Vfs=immunogenic,
            dur.days1=10,
            dur.days2=7,
            dur.days3=5,
            dur.days_v=5,
            yinit.matrix= yinit.matrix,
            RR=0.85,# relative infectiousness of vaccine virus
            q=1,
            sigma1=0.76,
            sigma2=0.6,
            sigma3=0.4,
            time.step='month',
            c2=contactmatrix,
            b1=b1,
            phi=phi,
            baseline.txn.rate = baseline.txn.rate
            )

results <- ode(y=yinit.vector, t=my_times,  
               func=livevac_booster, 
            parms=parms_livevac_dynamics)
   
   St <- results[,-1]
   q=1
   c2=parms_livevac_dynamics$c2
   beta= parms_livevac_dynamics$baseline.txn.rate/(parms_livevac_dynamics$dur.days1/30.44)/(sum(yinit.matrix)^(1-q))*c2
   b1= parms_livevac_dynamics$b1
   phi=parms_livevac_dynamics$phi
   rho1=parms_livevac_dynamics$rho1
   rho2=parms_livevac_dynamics$rho2
   sigma1=parms_livevac_dynamics$sigma1
   sigma2=parms_livevac_dynamics$sigma2
   sigma3=parms_livevac_dynamics$sigma3
   t0=tmax
   I1 <- results[,grep('I1', colnames(results))]
   I2 <- results[,grep('I2', colnames(results))]
   I3 <- results[,grep('I3', colnames(results))]
   I4 <- results[,grep('I4', colnames(results))]
   Iv <- results[,grep('Iv', colnames(results))]
   S1 <- results[,grep('S1', colnames(results))]
   S2 <- results[,grep('S2', colnames(results))]
   S3 <- results[,grep('S3', colnames(results))]
   S0 <- results[,grep('S0', colnames(results))]
   V1 <- results[,grep('V1', colnames(results))]
   V2 <- results[,grep('V2', colnames(results))]
   lambda1=matrix(0,nrow=t0,ncol=al)#Force of infection
    for (t in 1:t0)
    {lambda1[t,] <- as.vector((1+b1*cos(2*pi*(t-phi*12)/12))*((I1[t,]+rho1*I2[t,]+rho2*I3[t,]+rho2*I4[t,])%*%beta)/sum(St[t,]))}
   
   H1=matrix(0,nrow=t0,ncol=al)#Number of hospitalizations by age
   for (i in 1:al){
     H1[,i]=report_ratio*(hosp1[i]*S0[,i]*lambda1[,i]+hosp2[i]*sigma1*S1[,i]*lambda1[,i]+hosp3[i]*sigma2*S2[,i]*lambda1[,i]+hosp3[i]*sigma3*S3[,i]*lambda1[,i]+hosp2[i]*sigma1*lambda1[,i]*V1[,i]+hosp3[i]*sigma2*V2[,i]*lambda1[,i])
     age_dist[i] <- sum(H1[337:348,i])}
   
    
   #H <- rowSums(H1)
   H <- H1[253:(252+108),]
   livevac_agedist[j,] <- age_dist/agep*100000
   livevac_output[j,,] <-H
     if(j %% 10==0) {
      # Print on the screen some message 
      cat(paste0("percent: ", j/10, "%"))
   }
}

```

```{r}
live_v_booster <-matrix(nrow=8,ncol=3)
for (i in 1:8) {
live_v_booster[i,] <-
round(quantile((1-rowSums(livevac_output[,85:96,i])/rowSums(Novac_Hosp[,85:96,i]))*100,c(0.5,0.025,0.975)))}

round(quantile((1-rowSums(livevac_output[,85:96,1:8])/rowSums(Novac_Hosp[,85:96,1:8]))*100,c(0.5,0.025,0.975)))

write.csv(live_v_booster,"D:/RSVvac_output/tables/live_v_booster.csv")

```

