---
title: "livevac_cohort"
author: "Zhe Zheng"
date: "2/9/2022"
output: html_document
---

```{r}
# equilibrium status of RSV epidemics in four states using parameter estimates from maximum likelihood estimates
data_nj <- readRDS("C:/Users/70914/Box/aim3/RSVtransmissionmodel/data_and_parms/staninput/stan_initial_y_nj.rds")
data_ny <- readRDS("C:/Users/70914/Box/aim3/RSVtransmissionmodel/data_and_parms/staninput/stan_initial_y_ny.rds")
data_ca <- readRDS("C:/Users/70914/Box/aim3/RSVtransmissionmodel/data_and_parms/staninput/stan_initial_y_ca.rds")
data_wa <- readRDS("C:/Users/70914/Box/aim3/RSVtransmissionmodel/data_and_parms/staninput/stan_initial_y_wa.rds")

# initialize a 13*11 matrix and a vector length 143 that contains 13 age groups and 11 transmission/vaccination compartments
yinit.matrix= matrix(c(data_nj+data_ny+data_ca+data_wa),nrow=13,ncol=9)
dimnames(yinit.matrix)[[2]] <-c('M','S0','I1','S1','I2','S2','I3','S3','I4')
dimnames(yinit.matrix)[[1]] <-c("<2m","2-3m","4-5m","6-7m","8-9m","10-11m","1Y","2-4Y","5-9Y","10-19Y","20-39Y","40-59Y","60Y+")
yinit.frame= data.frame(yinit.matrix)
yinit.frame= add_column(yinit.frame,Iv = rep(0,13), .after = "I1") # Iv stands for just got vaccinated and can shed
# vaccine virus to others
yinit.frame= add_column(yinit.frame,Sv = rep(0,13), .after = "Iv") # Sv stands for a lower susceptibility to infections
# because of vaccination
yinit.matrix=  as.matrix(yinit.frame)
yinit.vector <- as.vector(yinit.matrix) #Vectorize the ynit matrix
name.array <- array(NA, dim=dim(yinit.matrix))
for(i in 1:dim(name.array)[1]){
  for(j in 1:dim(name.array)[2]){
      name.array[i,j] <- paste(dimnames(yinit.matrix)[[1]][i],dimnames(yinit.matrix)[[2]][j]  )
    }
  }

name.vector <- as.vector(name.array)
names(yinit.vector) <- name.vector

t0=tmax=348
my_times<- seq(1, tmax, by = 1) 

nsim=1000
al=13
```


```{r}
livevac_cohort<- function(t,y,parms, time.step='month'){
  
  States<-array(y, dim=dim(parms$yinit.matrix))
  dimnames(States) <- dimnames(parms$yinit.matrix)
  um=parms$um
  
  if(parms$time.step=='month'){
    period=12
    length.step=30.44 #days
  }else if(parms$time.step=='week'){
    period=52.1775
    length.step=7 #days
  }
  
  omega = 1/(parms$DurationMatImmunityDays/length.step)
  
  mu= 1/parms$WidthAgeClassMonth
  if(parms$time.step=='week'){
    mu= 1/(WidthAgeClassMonth*4.345)
  }
  
  gamma1= 1/(parms$dur.days1/length.step)  #converts 1/days to 1/lenth.step
  gamma2= 1/(parms$dur.days2/length.step)  
  gamma3= 1/(parms$dur.days3/length.step)  
  gamma4= gamma3  #gamma3 stands for rate of recovery from subsequent infection
  gamma_v= 1/(parms$dur.days_v/length.step)
  

	 Cfs = parms$Cfs*parms$VacPro[t]  # vaccine coverage will be informed by pediatric vaccine coverage

  
	#read in vaccination efficacy, based on live-attenuated vaccine immunogenic
   Vfs = parms$Vfs
   
  
  #Pull out the states  for the model as vectors
  M <-  States[,'M']
  S0 <-  States[,'S0']
  I1 <-  States[,'I1']
  
  Iv <-  States[,'Iv']
  Sv <-  States[,'Sv']
  
  S1 <-  States[,'S1']
  I2 <-  States[,'I2']
  
  S2 <-  States[,'S2']
  I3 <-  States[,'I3']
  
  S3 <-  States[,'S3']
  I4 <-  States[,'I4']
  
  
  N.ages <- length(M)
  
  ##fixed lambda parameter##################
  lambda <- parms$lambda[t,]
  lambda_v <- 0  # lambda_v= transmissibility of vaccine virus * number of vaccinated individuals
  # that shed vaccine virus currently

  ##########?????????????????##########################  
  
  dy <- matrix(NA, nrow=N.ages, ncol=ncol(States))
  colnames(dy) <- colnames(States)
  
  period.birth.rate <- log(parms$PerCapitaBirthsYear[t,]+1)/period #B=annual birth rate
  
  #https://journals.plos.org/plospathogens/article/file?id=10.1371/journal.ppat.1004591.s016&type=supplementary
  #mu represents aging to the next class
  #um is death rate
  
  Aging.Prop <- c(0,mu[1:(N.ages-1)])
  
  dy[,'M'] <- period.birth.rate*sum(States) - 
    (omega+(mu+um))*M +
   c(0,M[1:(N.ages-1)])*Aging.Prop -
     c(0,M[1:(N.ages-1)])*c(0,Cfs*Vfs,rep(0,N.ages-2))*Aging.Prop
  
  dy[,'S0'] <- omega*M -
    lambda*S0 -
    (mu + um)*S0 + 
    Aging.Prop*c(0,S0[1:(N.ages-1)]) -
    c(0,Cfs*Vfs,rep(0,N.ages-2))*Aging.Prop*c(0,S0[1:(N.ages-1)]) -
    lambda_v*S0
  
  dy[,'I1'] <-   lambda*S0 - 
    (gamma1 + mu + um)*I1 + 
    Aging.Prop*c(0,I1[1:(N.ages-1)]) 
 
  # Iv stands for just got vaccinated and can shed vaccine virus to others
  # a proportion of infants that are 2-3 month old will leave M and S0 and enter Iv
  # because they receive live attenuated vaccine at that time; correspond to the expected vaccination schedule
  dy[,'Iv'] <-  c(0,M[1:(N.ages-1)])*c(0,Cfs*Vfs,rep(0,N.ages-2))*Aging.Prop +
     c(0,Cfs*Vfs,rep(0,N.ages-2))*Aging.Prop*c(0,S0[1:(N.ages-1)]) +  
     lambda_v*S0 -
     ( mu + um)*Iv + 
     Aging.Prop*c(0,Iv[1:(N.ages-1)]) - 
     gamma_v*Iv
 
  # when the infants stop shedding vaccine virus, they enter the Sv compartment
  # we assumed their susceptibility to infections is now equal to after a natural infection (S1) because of vaccination 
  dy[,'Sv'] <-   gamma_v*Iv - 
    parms$sigma1*lambda*Sv -
    (mu+um)*Sv + 
    Aging.Prop*c(0,Sv[1:(N.ages-1)])
  
  # the rest is very similar to the original transmission model
  dy[,'S1'] <- gamma1*I1 - 
    parms$sigma1*lambda*S1 - 
    (mu+um)*S1 + 
    Aging.Prop*c(0,S1[1:(N.ages-1)])
  
  dy[,'I2'] <- parms$sigma1*lambda*S1 +
    parms$sigma1*lambda*Sv - 
    gamma2*I2-(mu + um)*I2 + 
    Aging.Prop*c(0,I2[1:(N.ages-1)]) 
  
  dy[,'S2'] <- gamma2*I2 - 
    parms$sigma2*lambda*S2 -
    (mu+um)*S2+ 
    Aging.Prop*c(0,S2[1:(N.ages-1)]) 
  
  dy[,'I3'] <- parms$sigma2*lambda*S2 -
    (gamma3 + mu+um)*I3 +  
    Aging.Prop*c(0,I3[1:(N.ages-1)]) 
  
  dy[,'S3'] <- gamma3*I3 +  
    gamma4*I4 -
    parms$sigma3*lambda*S3 -
    (mu + um)*S3 + 
    Aging.Prop*c(0,S3[1:(N.ages-1)])
  
  dy[,'I4'] <- parms$sigma3*lambda*S3 - 
    gamma4*I4 - 
    (mu + um)*I4 + 
    Aging.Prop*c(0,I4[1:(N.ages-1)]) 
  
  
  
  
  derivs <- as.vector(dy)
  
  res <- list(derivs)
  
  return(res)
}

```

```{r}
livevac_output_direct <- array(dim=c(nsim,12,al))

  for(j in 1:nsim){
  immunogenic <- params.set[j,3]
  coverage <- params.set[j,4]
  fix_lambda=Novac_lambda[j,,]
  omega=params.set[j,9]
  hosp_ratio=params.set[j,10]
  
 parms_livevac_cohort<-list(PerCapitaBirthsYear=as.matrix(birthrate),
            DurationMatImmunityDays=1/omega*30.44,
            WidthAgeClassMonth=1/data_msis$u,
            um=-0.0005,
            rho1=0.75,
            rho2=0.51,
            VacPro=c(rep(0,264),rep(1,348-264)),
            Cfs=coverage,
            Vfs=immunogenic,
            dur.days1=10,
            dur.days2=7,
            dur.days3=5,
            dur.days_v=5,
            yinit.matrix= yinit.matrix,
            RR=0.85,
            q=1,
            sigma1=0.76,
            sigma2=0.6,
            sigma3=0.4,
            time.step='month',
            c2=contactmatrix,
            lambda=fix_lambda
            )

results <- ode(y=yinit.vector, t=my_times,  
               func=livevac_cohort, 
            parms=parms_livevac_cohort)

   St <- results[,-1]
   q=1
   c2=parms_livevac_cohort$c2
   rho1=parms_livevac_cohort$rho1
   rho2=parms_livevac_cohort$rho2
   sigma1=parms_livevac_cohort$sigma1
   sigma2=parms_livevac_cohort$sigma2
   sigma3=parms_livevac_cohort$sigma3
    t0=tmax
   I1 <- results[,grep('I1', colnames(results))]
   I2 <- results[,grep('I2', colnames(results))]
   I3 <- results[,grep('I3', colnames(results))]
   I4 <- results[,grep('I4', colnames(results))]
   S1 <- results[,grep('S1', colnames(results))]
   S2 <- results[,grep('S2', colnames(results))]
   S3 <- results[,grep('S3', colnames(results))]
   S0 <- results[,grep('S0', colnames(results))]
   Sv <- results[,grep('Sv', colnames(results))]
   
   lambda1 <- fix_lambda[(1:348),]
   
   H1=matrix(0,nrow=t0,ncol=al)#Number of hospitalizations by age
      for (i in 1:al){
     H1[,i]=hosp_ratio*(hosp1[i]*S0[,i]*lambda1[,i]+hosp2[i]*sigma1*S1[,i]*lambda1[,i]+hosp3[i]*sigma2*S2[,i]*lambda1[,i]+hosp3[i]*sigma3*S3[,i]*lambda1[,i]+hosp2[i]*sigma1*Sv[,i]*lambda1[,i])}
   
   livevac_output_direct[j,,] <- H1[(337:348),]
   
   if(j %% 10==0) {
      # Print on the screen some message
      cat(paste0("percent: ", j/10, "%"))
   }
  }
```

```{r}
source("C:/Users/70914/Box/aim3/RSVtransmissionmodel/Model_source/livevac_dynamics.R")
livevac_output_total <- array(dim=c(nsim,12,al))

  for(j in 1:nsim){
  immunogenic <- params.set[j,3]
  coverage <- params.set[j,4]
  omega=params.set[j,9]
  hosp_ratio=params.set[j,10]
  baseline.txn.rate=params.set[j,6]
  b1=params.set[j,8]
  phi=params.set[j,7]

  
 parms_livevac_dynamics<-list(PerCapitaBirthsYear=as.matrix(birthrate),
            DurationMatImmunityDays=1/omega*30.44,
            WidthAgeClassMonth=1/data_msis$u,
            um=-0.0005,
            rho1=0.75,
            rho2=0.51,
            VacPro=c(rep(0,264),rep(1,348-264)),
             #c(rep(0,264),rep(c(0,0,0,0,1,1,1,1,1,0,0,0),(348-264)/12)),
            Cfs=coverage,
            Vfs=immunogenic,
            dur.days1=10,
            dur.days2=7,
            dur.days3=5,
            dur.days_v=5,
            yinit.matrix= yinit.matrix,
            RR=0.85,
            q=1,
            sigma1=0.76,
            sigma2=0.6,
            sigma3=0.4,
            time.step='month',
            c2=contactmatrix,
            b1=b1,
            phi=phi,
            baseline.txn.rate = baseline.txn.rate
            )

results <- ode(y=yinit.vector, t=my_times,  
               func=livevac_dynamics, 
            parms=parms_livevac_dynamics)
   
   St <- results[,-1]
   q=1
   c2=parms_livevac_dynamics$c2
   beta= parms_livevac_dynamics$baseline.txn.rate/(parms_livevac_dynamics$dur.days1/30.44)/(sum(yinit.matrix)^(1-q))*c2
   b1= parms_livevac_dynamics$b1
   phi=parms_livevac_dynamics$phi
   rho1=parms_livevac_dynamics$rho1
   rho2=parms_livevac_dynamics$rho2
   sigma1=parms_livevac_dynamics$sigma1
   sigma2=parms_livevac_dynamics$sigma2
   sigma3=parms_livevac_dynamics$sigma3
   t0=tmax
   I1 <- results[,grep('I1', colnames(results))]
   I2 <- results[,grep('I2', colnames(results))]
   I3 <- results[,grep('I3', colnames(results))]
   I4 <- results[,grep('I4', colnames(results))]
   Iv <- results[,grep('Iv', colnames(results))]
   S1 <- results[,grep('S1', colnames(results))]
   S2 <- results[,grep('S2', colnames(results))]
   S3 <- results[,grep('S3', colnames(results))]
   S0 <- results[,grep('S0', colnames(results))]
   Sv <- results[,grep('Sv', colnames(results))]
   lambda1=matrix(0,nrow=t0,ncol=al)#Force of infection
    for (t in 1:t0)
    {lambda1[t,] <- as.vector((1+b1*cos(2*pi*(t-phi*12)/12))*((I1[t,]+rho1*I2[t,]+rho2*I3[t,]+rho2*I4[t,])%*%beta)/sum(St[t,]))}
   
   H1=matrix(0,nrow=t0,ncol=al)#Number of hospitalizations by age
   for (i in 1:al){
     H1[,i]=hosp_ratio*(hosp1[i]*S0[,i]*lambda1[,i]+hosp2[i]*sigma1*S1[,i]*lambda1[,i]+hosp3[i]*sigma2*S2[,i]*lambda1[,i]+hosp3[i]*sigma3*S3[,i]*lambda1[,i]+hosp2[i]*sigma1*Sv[,i]*lambda1[,i])}
   
   livevac_output_total[j,,] <- H1[(337:348),]
   
   if(j %% 10==0) {
      # Print on the screen some message
      cat(paste0("percent: ", j/10, "%"))
   }
  }
```

